var fs = require('fs')
var json2scss = require('json2scss-map')
// import data from "../../../apps/guide/src/data"

var files = ['colors', 'typography']

files.forEach(file => {
  fs.copyFile(`tokens/_${file}.json`, `../../apps/guide/src/data/${file}.json`, err => {
    if (err) {
      console.log('Error Found:', err)
    } else {
      console.log('Copied succesfully:')
    }
  })

  fs.createReadStream(`tokens/_${file}.json`)
    .pipe(
      json2scss({
        prefix: `$${file}: `,
        cl4Syntax: true,
      })
    )
    // .pipe(fs.appendFileSync('Generated by Sproutkit', 'tokens/_colors.json', 'utf8'))
    .pipe(fs.createWriteStream(`scss/library/tokens/_${file}.scss`))
})
